title: Authelia Just the Docs Test Site
description: Just for testing markdown to html stuff
remote_theme: pmarsceill/just-the-docs
search_enabled: false
exclude:
- Gemfile
- Gemfile.lock
- .gitignore
